"""create agent outputs table

Revision ID: 08d0703d3109
Revises: a3c187396cf8
Create Date: 2026-08-19 23:46:19.483251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08d0703d3109'
down_revision: Union[str, Sequence[str], None] = 'a3c187396cf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('agent_type', sa.String(length=30), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_outputs_agent_type'), 'agent_outputs', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agent_outputs_id'), 'agent_outputs', ['id'], unique=False)
    op.create_index(op.f('ix_agent_outputs_project_id'), 'agent_outputs', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_outputs_project_id'), table_name='agent_outputs')
    op.drop_index(op.f('ix_agent_outputs_id'), table_name='agent_outputs')
    op.drop_index(op.f('ix_agent_outputs_agent_type'), table_name='agent_outputs')
    op.drop_table('agent_outputs')
    # ### end Alembic commands ###
